"""Built-in email templates used by the Templates tab."""

TEMPLATES = {
    "Internship Request": "Subject: Internship opportunity inquiry\n\nDear [Name],\n\nI am [Your Name], a [year/program] student interested in [field]. I admire [company/team] because [reason]. I would be grateful for the opportunity to contribute and learn through an internship.\n\nThank you for your time.\n\nSincerely,\n[Your Name]",
    "Cold Email": "Subject: Connecting about [topic]\n\nHello [Name],\n\nI came across your work on [topic] and was impressed by [specific detail]. I am currently [brief background] and would value the chance to learn from your perspective.\n\nWould you be open to a brief conversation?\n\nBest regards,\n[Your Name]",
    "Referral Request": "Subject: Referral request for [role]\n\nHi [Name],\n\nI hope you are well. I noticed the [role] opening at [company] and believe my experience in [skills] aligns well. If you are comfortable, would you consider referring me? I have attached my resume for context.\n\nThank you,\n[Your Name]",
    "Thank You": "Subject: Thank you\n\nDear [Name],\n\nThank you for [specific help/opportunity]. I truly appreciate your time and support. [Optional personal detail.]\n\nWarm regards,\n[Your Name]",
    "Interview Follow-up": "Subject: Thank you for the interview — [Role]\n\nDear [Name],\n\nThank you for discussing the [Role] position today. I enjoyed learning about [topic]. Our conversation reinforced my interest in contributing my [relevant skill] to the team.\n\nSincerely,\n[Your Name]",
    "Resignation": "Subject: Resignation — [Your Name]\n\nDear [Manager Name],\n\nPlease accept this email as formal notice of my resignation from [Company], effective [last working day]. I am grateful for the opportunities and support I received here. I will do my best to ensure a smooth handover.\n\nSincerely,\n[Your Name]",
    "Meeting Request": "Subject: Request for a meeting — [topic]\n\nHello [Name],\n\nI would appreciate the opportunity to discuss [topic] with you. Would you be available for a brief meeting during [timeframe]? I am happy to work around your schedule.\n\nBest,\n[Your Name]",
    "Networking": "Subject: Connecting with a fellow [field] professional\n\nHello [Name],\n\nI am [Your Name], a [brief background] interested in [field]. I found your profile while exploring [area] and would be glad to connect and learn about your experience.\n\nBest regards,\n[Your Name]",
    "Offer Acceptance": "Subject: Acceptance of [Role] offer\n\nDear [Name],\n\nI am delighted to accept the offer for the [Role] position at [Company]. Thank you for this opportunity. I look forward to joining the team on [start date].\n\nSincerely,\n[Your Name]",
    "Offer Rejection": "Subject: Regarding the [Role] offer\n\nDear [Name],\n\nThank you very much for offering me the [Role] position at [Company]. After careful consideration, I have decided to decline the offer. I sincerely appreciate your time and wish the team continued success.\n\nKind regards,\n[Your Name]",
}
